name: Run

on: 
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install r req.txt
    - name: Run
      run: |
        python ./cityboxantwerpchecker.py ${{secrets.SENDER}} ${{secret.RECIVER}} ${{secret.PASSWORD}} 2025-02-25 2025-03-03
